language: python

sudo: required

install:
- sudo apt-get install pandoc libzmq
- sudo pip install --allow-all-external --pre -r docs/requirements.txt --use-mirrors

before_script:
- git config --global push.default simple
- git config --global user.name "Olga Botvinnik"
- git config --global user.email "olga.botvinnik@gmail.com"
- export REPO_URL_GITHUB="https://$GH_TOKEN@github.com/$GH_REPO.git"
- . ./.travis/setup.sh
- echo $DEPLOY_HTML_DIR

script:
  - echo "script!"

after_script:
- cd docs
- make setup_gh_pages
- make generate
- cp geo_submission_example.xls _build/html
- make deploy

env:
  global:
  - GH_REPO="YeoLab/onboarding"
  - secure: Y8AbQwnpTwfme6II24Klxjbg83ISTB7z+Uj1XxicbMlQsKs0UP5PsaJnY0+mi+HJMoQXYXjsWpoPbxehjLYHdPICYIcK+9zoaoRj504wEjwFEAXzqzzQVfCTJuAvNnwgo/s2dQGmBb8kr4Tkiio3Q/K+ax05rsM5sU4dw6ALRIk=
